# Generated by Django 4.2 on 2024-05-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 25, 23, 41, 43, 594625), null=True, verbose_name='入职时间'),
        ),
    ]
