# Generated by Django 4.2 on 2024-05-25 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_myadmin_is_superadmin_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myadmin',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='是否是超级管理员'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 25, 23, 48, 0, 942255), null=True, verbose_name='入职时间'),
        ),
    ]
