# Generated by Django 4.2 on 2024-05-25 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_myadmin_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 26, 1, 30, 37, 163665), null=True, verbose_name='入职时间'),
        ),
    ]
