# Generated by Django 3.0.6 on 2024-05-27 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20240527_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 27, 16, 30, 57, 369907), null=True, verbose_name='入职时间'),
        ),
    ]
